# Generated by Django 3.0.3 on 2020-09-06 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PREDICTION_CHART',
        ),
        migrations.DeleteModel(
            name='Registry',
        ),
        migrations.DeleteModel(
            name='business',
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.DeleteModel(
            name='DfReview_test',
        ),
        migrations.DeleteModel(
            name='DfReview_train',
        ),
        migrations.DeleteModel(
            name='Document_features',
        ),
        migrations.DeleteModel(
            name='ItemItem',
        ),
        migrations.DeleteModel(
            name='Prediction',
        ),
        migrations.DeleteModel(
            name='review',
        ),
        migrations.DeleteModel(
            name='tip',
        ),
        migrations.DeleteModel(
            name='userData',
        ),
    ]
